// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsKdGPa3YcyrCRBlg53EPGcZ5NOTArpUA',
    appId: '1:178803271368:web:303e023fae1e168eb5a7fd',
    messagingSenderId: '178803271368',
    projectId: 'flutter-app-07',
    authDomain: 'flutter-app-07.firebaseapp.com',
    storageBucket: 'flutter-app-07.appspot.com',
    measurementId: 'G-0BH8DYHCH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASD8x4HehKK6rvPeLlB3QdeKjYu7aSU_Q',
    appId: '1:178803271368:android:380ec3c3fb2674a9b5a7fd',
    messagingSenderId: '178803271368',
    projectId: 'flutter-app-07',
    storageBucket: 'flutter-app-07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVuk3N7G-Rpb9xghTf-JB_S6HogIQxWro',
    appId: '1:178803271368:ios:8481e5a95242b62ab5a7fd',
    messagingSenderId: '178803271368',
    projectId: 'flutter-app-07',
    storageBucket: 'flutter-app-07.appspot.com',
    iosBundleId: 'com.example.firebaseDataApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVuk3N7G-Rpb9xghTf-JB_S6HogIQxWro',
    appId: '1:178803271368:ios:8481e5a95242b62ab5a7fd',
    messagingSenderId: '178803271368',
    projectId: 'flutter-app-07',
    storageBucket: 'flutter-app-07.appspot.com',
    iosBundleId: 'com.example.firebaseDataApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsKdGPa3YcyrCRBlg53EPGcZ5NOTArpUA',
    appId: '1:178803271368:web:a671f4edba1c753fb5a7fd',
    messagingSenderId: '178803271368',
    projectId: 'flutter-app-07',
    authDomain: 'flutter-app-07.firebaseapp.com',
    storageBucket: 'flutter-app-07.appspot.com',
    measurementId: 'G-M961CY7E4F',
  );

}